version: '3.8'

services:
  app:
    image: bloodyexecutor/ec2:latest
    container_name: ec2
    restart: always
    ports:
      - '80:3000'
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
