version: '3'

services:
  app:
    image: bloodyexecutor/ec2:latest
    container_name: ec2
    restart: always
    ports:
      - '80:3000'
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
